"""后台任务侧枚举。"""

from enum import Enum


class JobType(str, Enum):
    FETCH_URL = "FETCH_URL"
    PARSE_DOCUMENT = "PARSE_DOCUMENT"
    GENERATE_EVIDENCE = "GENERATE_EVIDENCE"
    PARSE_DATASET = "PARSE_DATASET"
    GENERATE_ANALYSIS_PLAN = "GENERATE_ANALYSIS_PLAN"
    GENERATE_CODE_TASK = "GENERATE_CODE_TASK"
    EXECUTE_CODE_TASK = "EXECUTE_CODE_TASK"
    GENERATE_OUTLINE = "GENERATE_OUTLINE"
    GENERATE_WORD = "GENERATE_WORD"
    GENERATE_PPT = "GENERATE_PPT"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
