"""后台任务侧枚举。"""

from enum import Enum


class JobType(str, Enum):
    FETCH_URL = "FETCH_URL"
    PARSE_DOCUMENT = "PARSE_DOCUMENT"
    GENERATE_EVIDENCE = "GENERATE_EVIDENCE"
    PARSE_DATASET = "PARSE_DATASET"
    GENERATE_ANALYSIS_PLAN = "GENERATE_ANALYSIS_PLAN"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
