"""来源与证据侧枚举。"""

from enum import Enum


class SourceKind(str, Enum):
    URL = "URL"
    FILE = "FILE"


class SourceStatus(str, Enum):
    PENDING = "PENDING"
    FETCHED = "FETCHED"
    PARSED = "PARSED"
    FAILED = "FAILED"
    DELETED = "DELETED"


class EvidenceType(str, Enum):
    BACKGROUND = "BACKGROUND"
    METHOD = "METHOD"
    RESULT = "RESULT"
    CONCLUSION = "CONCLUSION"
    LIMITATION = "LIMITATION"
    REFERENCE = "REFERENCE"


class EvidenceCardStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    STALE = "STALE"


class CandidateSource(str, Enum):
    MODEL = "MODEL"
    LOCAL_RULE = "LOCAL_RULE"
    MANUAL = "MANUAL"


class SourceChangeType(str, Enum):
    SOURCE_CREATED = "SOURCE_CREATED"
    SOURCE_FETCHED = "SOURCE_FETCHED"
    SOURCE_PARSED = "SOURCE_PARSED"
    SOURCE_DELETED = "SOURCE_DELETED"
    SOURCES_COMPLETED = "SOURCES_COMPLETED"
    EVIDENCE_CARD_GENERATED = "EVIDENCE_CARD_GENERATED"
    EVIDENCE_CARD_UPDATED = "EVIDENCE_CARD_UPDATED"
    EVIDENCE_CARD_CONFIRMED = "EVIDENCE_CARD_CONFIRMED"
    EVIDENCE_CARD_REJECTED = "EVIDENCE_CARD_REJECTED"
    EVIDENCE_COMPLETED = "EVIDENCE_COMPLETED"
