"""项目状态枚举。

SPEC 0001 第一切片只需要 DRAFT 状态，但为后续完整状态机预留位置。
"""

from enum import Enum


class ProjectStatus(str, Enum):
    DRAFT = "DRAFT"
    REQUIREMENT_PARSED = "REQUIREMENT_PARSED"
    REQUIREMENT_CONFIRMED = "REQUIREMENT_CONFIRMED"
    SOURCES_COLLECTED = "SOURCES_COLLECTED"
    EVIDENCE_DRAFTED = "EVIDENCE_DRAFTED"
    EVIDENCE_CONFIRMED = "EVIDENCE_CONFIRMED"
    DATASET_READY = "DATASET_READY"
    FEASIBILITY_CHECKED = "FEASIBILITY_CHECKED"
    ANALYSIS_PLANNED = "ANALYSIS_PLANNED"
    ANALYSIS_CONFIRMED = "ANALYSIS_CONFIRMED"
    CODE_DRAFTED = "CODE_DRAFTED"
    CODE_CONFIRMED = "CODE_CONFIRMED"
    EXECUTING = "EXECUTING"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    RESULT_CONFIRMED = "RESULT_CONFIRMED"
    OUTLINE_CONFIRMED = "OUTLINE_CONFIRMED"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
